# Generated by Django 3.2.9 on 2021-12-09 16:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_uz', models.CharField(max_length=200)),
                ('category_name_ru', models.CharField(max_length=200)),
                ('category_name_us', models.CharField(blank=True, max_length=200)),
                ('category_name_tr', models.CharField(blank=True, max_length=200)),
                ('category_img', models.ImageField(upload_to='categories/')),
                ('counter_total_product', models.IntegerField(default=0)),
                ('category_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': '2. Категории',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_icon', models.ImageField(upload_to='company/')),
                ('company_short_info', models.CharField(max_length=150)),
                ('company_info', models.TextField()),
                ('company_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': '3.1 Компании',
            },
        ),
        migrations.CreateModel(
            name='ecology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecology_img', models.ImageField(upload_to='ecology/')),
                ('ecology_desc', models.TextField()),
                ('ecology_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Экология',
                'verbose_name_plural': '3.3.3 Экологии',
            },
        ),
        migrations.CreateModel(
            name='exports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('country_icon', models.ImageField(upload_to='exports/')),
                ('export_percent_before', models.FloatField(default=0, max_length=100)),
                ('export_percent_after', models.FloatField(default=0, max_length=100)),
                ('export_year_before', models.CharField(max_length=4)),
                ('export_year_after', models.CharField(max_length=4)),
                ('export_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Экспорт',
                'verbose_name_plural': '3.3.2 Экспорты',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('comment', models.TextField()),
                ('feedback_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': '3.3.5 Отзывы',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
                ('title_us', models.CharField(blank=True, max_length=150)),
                ('title_tr', models.CharField(blank=True, max_length=150)),
                ('section_name_uz_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('section_name_ru_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('section_name_us_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None)),
                ('section_name_tr_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None)),
                ('section_description_uz_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('section_description_ru_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('section_description_us_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None)),
                ('section_description_tr_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None)),
                ('good_create_date', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.categories')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': '2.1 Товары',
            },
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_section', models.CharField(max_length=150)),
                ('comp_icon', models.ImageField(upload_to='info/')),
                ('info_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': '3.3 Информации',
            },
        ),
        migrations.CreateModel(
            name='innovations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_img', models.ImageField(upload_to='innovations/')),
                ('innovation_desc', models.TextField()),
                ('innovation_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инноватция',
                'verbose_name_plural': '3.3.4 Инноватции',
            },
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_lang', models.CharField(choices=[('Uzbek', 'O`zbek tili'), ('English', 'English'), ('Russian', 'Русский язык'), ('Turkey', 'Turk dili')], max_length=20)),
                ('language_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': '1. Языки',
            },
        ),
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_img', models.ImageField(upload_to='partners/')),
                ('partner_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': '3.3.1 Партнеры',
            },
        ),
        migrations.CreateModel(
            name='product_bases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bases_img', models.ImageField(upload_to='ecology/')),
                ('product_bases_desc', models.CharField(max_length=150)),
                ('product_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'База продукта',
                'verbose_name_plural': '3.3.6 База продуктов',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_city', models.CharField(max_length=150)),
                ('service_address_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=None)),
                ('service_phone', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': '3.3.7 Сервисы',
            },
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
                ('title_us', models.CharField(blank=True, max_length=150)),
                ('title_tr', models.CharField(blank=True, max_length=150)),
                ('icon', models.ImageField(upload_to='stocks/icon/')),
                ('banner', models.ImageField(upload_to='stocks/banner/')),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_us', models.TextField(blank=True)),
                ('description_tr', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stock_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': '4.4 Акции',
            },
        ),
        migrations.CreateModel(
            name='reportsOfLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_language', models.IntegerField(default=0)),
                ('lang_rep_category_create_date', models.DateField(auto_now=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.languages')),
            ],
            options={
                'verbose_name': 'Отчет по языку',
                'verbose_name_plural': '4.1 Отчеты по языкам',
            },
        ),
        migrations.CreateModel(
            name='reportsOfGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_good', models.IntegerField(default=0)),
                ('good_rep_category_create_date', models.DateField(auto_now=True)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.goods')),
            ],
            options={
                'verbose_name': 'Отчет по продукту',
                'verbose_name_plural': '4.3 Отчеты по продуктам',
            },
        ),
        migrations.CreateModel(
            name='reportsOfCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_category', models.IntegerField(default=0)),
                ('cat_rep_category_create_date', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.categories')),
            ],
            options={
                'verbose_name': 'Отчет по категорие',
                'verbose_name_plural': '4.2 Отчеты по категории',
            },
        ),
        migrations.CreateModel(
            name='good_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_img', models.ImageField(upload_to='goods/')),
                ('good_badge', models.ImageField(upload_to='badges/')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.goods')),
            ],
            options={
                'verbose_name': 'Картина Товара',
                'verbose_name_plural': '2.2 Картинки Товара',
            },
        ),
    ]
