# Generated by Django 3.2.9 on 2022-01-04 19:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_uz', models.CharField(max_length=200, verbose_name='Узбекский')),
                ('category_name_ru', models.CharField(max_length=200, verbose_name='Русский')),
                ('category_name_us', models.CharField(blank=True, max_length=200, verbose_name='Английский')),
                ('category_name_tr', models.CharField(blank=True, max_length=200, verbose_name='Турецкий')),
                ('category_img', models.ImageField(upload_to='categories/', verbose_name='Икона')),
                ('counter_total_product', models.IntegerField(default=0, verbose_name='Cчетчик продуктов')),
                ('category_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': '1. Категории',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_icon', models.ImageField(upload_to='company/', verbose_name='значок компании')),
                ('company_short_info', models.CharField(max_length=150, verbose_name='Название')),
                ('company_info', models.TextField(verbose_name='Информация')),
                ('company_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информацию о компании',
                'verbose_name_plural': '5. О нас -> Информацию компании',
            },
        ),
        migrations.CreateModel(
            name='ecology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecology_img', models.ImageField(upload_to='ecology/', verbose_name='Изображениe')),
                ('ecology_desc', models.TextField(verbose_name='Описание')),
                ('ecology_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Экологию',
                'verbose_name_plural': '6.2 О нас -> Информации -> Экологии',
            },
        ),
        migrations.CreateModel(
            name='exports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('country_icon', models.ImageField(upload_to='exports/', verbose_name='Значок страны')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание на Узбекском')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание на Русском')),
                ('description_us', models.TextField(blank=True, verbose_name='Описание на Английском')),
                ('description_tr', models.TextField(blank=True, verbose_name='Описание на Турецком')),
                ('export_percent_before', models.FloatField(default=0, max_length=100, verbose_name='Проценты до')),
                ('export_percent_after', models.FloatField(default=0, max_length=100, verbose_name='Проценты после')),
                ('export_year_before', models.CharField(max_length=4, verbose_name='Годом ранее')),
                ('export_year_after', models.CharField(max_length=4, verbose_name='Год спустя')),
                ('export_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Экспорт',
                'verbose_name_plural': '6.1 О нас -> Информации -> Экспорты',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('comment', models.TextField()),
                ('feedback_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': '8. Отзывы',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=250)),
                ('title_ru', models.CharField(max_length=250)),
                ('title_us', models.CharField(blank=True, max_length=250)),
                ('title_tr', models.CharField(blank=True, max_length=250)),
                ('section_name_uz', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), size=None)),
                ('section_name_ru', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), size=None)),
                ('section_name_us', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None)),
                ('section_name_tr', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None)),
                ('section_description_uz', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999, null=True), size=None), size=None)),
                ('section_description_ru', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999, null=True), size=None), size=None)),
                ('section_description_us', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None)),
                ('section_description_tr', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None)),
                ('good_create_date', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': '2.1 Продукты',
            },
        ),
        migrations.CreateModel(
            name='innovations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_img', models.ImageField(upload_to='innovations/', verbose_name='Изображениe')),
                ('innovation_desc', models.TextField(verbose_name='Описание')),
                ('innovation_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информацию об инновации',
                'verbose_name_plural': '6.3 О нас -> Информации -> Инноватции',
            },
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_lang', models.CharField(choices=[('Uzbek', 'O`zbek tili'), ('English', 'English'), ('Russian', 'Русский язык'), ('Turkey', 'Turk dili')], max_length=20)),
                ('language_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_img', models.ImageField(upload_to='partners/', verbose_name='Значки брендов')),
                ('partner_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнера',
                'verbose_name_plural': '4. Партнеры',
            },
        ),
        migrations.CreateModel(
            name='product_bases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bases_img', models.ImageField(upload_to='ecology/', verbose_name='Изображениe')),
                ('product_bases_desc', models.CharField(max_length=150, verbose_name='Описание')),
                ('product_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Производственную базу',
                'verbose_name_plural': '6.4 О нас -> Информации -> База продуктов',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_city', models.CharField(max_length=150, verbose_name='Название города')),
                ('service_address_list', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), size=None), size=None)),
                ('service_phone', models.IntegerField(blank=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Сервисный центр',
                'verbose_name_plural': '6.5 О нас -> Информации -> Сервисы',
            },
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=150, verbose_name='Узбекский')),
                ('title_ru', models.CharField(max_length=150, verbose_name='Русский')),
                ('title_us', models.CharField(blank=True, max_length=150, verbose_name='Английский')),
                ('title_tr', models.CharField(blank=True, max_length=150, verbose_name='Турецкий')),
                ('icon', models.ImageField(upload_to='stocks/icon/', verbose_name='Икона')),
                ('banner', models.ImageField(upload_to='stocks/banner/', verbose_name='Баннер')),
                ('description_uz', models.TextField(verbose_name='Описание на узбекском')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_us', models.TextField(blank=True, verbose_name='Описание на английском')),
                ('description_tr', models.TextField(blank=True, verbose_name='Описание на турецком')),
                ('start_date', models.DateField(verbose_name='Дата стратра')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('stock_category_create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Акцию',
                'verbose_name_plural': '3. Акции',
            },
        ),
        migrations.CreateModel(
            name='reportsOfLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_language', models.IntegerField(default=0, verbose_name='Количество кликов')),
                ('lang_rep_category_create_date', models.DateField(auto_now=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.languages', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Отчет по языку',
                'verbose_name_plural': '7.1 Отчеты по языкам',
            },
        ),
        migrations.CreateModel(
            name='reportsOfGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_good', models.IntegerField(default=0, verbose_name='Количество кликов')),
                ('good_rep_category_create_date', models.DateField(auto_now=True)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.goods', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отчет по продукту',
                'verbose_name_plural': '7.3 Отчеты по продуктам',
            },
        ),
        migrations.CreateModel(
            name='reportsOfCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_category', models.IntegerField(default=0, verbose_name='Количество кликов')),
                ('cat_rep_category_create_date', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Отчет по категорие',
                'verbose_name_plural': '7.2 Отчеты по категории',
            },
        ),
        migrations.CreateModel(
            name='good_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_img', models.ImageField(blank=True, upload_to='goods/', verbose_name='Изображения')),
                ('good_badge', models.ImageField(blank=True, upload_to='badges/', verbose_name='Значок')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodImage', to='artelApp.goods', verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Изображение продукту',
                'verbose_name_plural': '2.2 Продукты -> Картинки ',
            },
        ),
    ]
