# Generated by Django 3.2.9 on 2022-01-07 19:36

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='counter_total_product',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='starts',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_description_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None, verbose_name='Опис Русский'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_description_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None, verbose_name='Опис Турецкий'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_description_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None, verbose_name='Опис Английский'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_description_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None, verbose_name='Опис Узбекский'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_name_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), size=None, verbose_name='Разд Рус'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_name_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None, verbose_name='Разд Тур'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_name_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), blank=True, size=None, verbose_name='Разд Анг'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='section_name_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None), size=None, verbose_name='Разд Узб'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_ru',
            field=models.CharField(max_length=250, verbose_name='Загл. Рус'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_tr',
            field=models.CharField(blank=True, max_length=250, verbose_name='Загл. Тур'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_us',
            field=models.CharField(blank=True, max_length=250, verbose_name='Загл. Анг'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_uz',
            field=models.CharField(max_length=250, verbose_name='Загл. Узб'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), size=None), size=None, verbose_name='Адресса'),
        ),
    ]
