# Generated by Django 4.0 on 2022-02-05 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': '7. Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='reportsofcategory',
            options={'verbose_name': 'Отчет по категориеи', 'verbose_name_plural': '8.2 Отчеты по категории'},
        ),
        migrations.AlterModelOptions(
            name='reportsofgood',
            options={'verbose_name': 'Отчет по продукту', 'verbose_name_plural': '8.3 Отчеты по продуктам'},
        ),
        migrations.AlterModelOptions(
            name='reportsoflanguage',
            options={'verbose_name': 'Отчет по языку', 'verbose_name_plural': '8.1 Отчеты по языкам'},
        ),
        migrations.AlterField(
            model_name='ecology',
            name='ecology_img',
            field=models.ImageField(upload_to='ecology/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='innovations',
            name='innovation_img',
            field=models.ImageField(upload_to='innovations/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product_bases',
            name='product_bases_img',
            field=models.ImageField(upload_to='ecology/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Адреса Рус'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None, verbose_name='Адреса Тур'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None, verbose_name='Адреса Анг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Адреса Узб'),
        ),
    ]
