# Generated by Django 3.2.9 on 2021-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='cat_name_tr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='cat_name_us',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
