# Generated by Django 3.2.9 on 2022-01-13 06:36

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='good_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name_uz', models.TextField(null=True, verbose_name='Секции Узб')),
                ('section_name_ru', models.TextField(null=True, verbose_name='Секции Рус')),
                ('section_name_us', models.TextField(blank=True, null=True, verbose_name='Секции Анг')),
                ('section_name_tr', models.TextField(blank=True, null=True, verbose_name='Секции Тур')),
            ],
            options={
                'verbose_name': 'Раздел продуктов',
                'verbose_name_plural': '2.3 Продукты -> Раздел',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_ru',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_tr',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_us',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_uz',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_ru',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_tr',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_us',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_uz',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_img',
            field=models.ImageField(null=True, upload_to='categories/', verbose_name='Икона'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Русский'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Турецкий'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name_us',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Английский'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Узбекский'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_info_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Информация Тур'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_info_us',
            field=models.TextField(blank=True, null=True, verbose_name='Информация Анг'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_short_info_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название Рус'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_short_info_tr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название Тур'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_short_info_us',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название Анг'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_short_info_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название Узб'),
        ),
        migrations.AlterField(
            model_name='ecology',
            name='ecology_desc_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Тур'),
        ),
        migrations.AlterField(
            model_name='ecology',
            name='ecology_desc_us',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Анг'),
        ),
        migrations.AlterField(
            model_name='exports',
            name='country_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Страна Рус'),
        ),
        migrations.AlterField(
            model_name='exports',
            name='country_tr',
            field=models.CharField(blank=True, max_length=250, verbose_name='Страна Тур'),
        ),
        migrations.AlterField(
            model_name='exports',
            name='country_us',
            field=models.CharField(blank=True, max_length=250, verbose_name='Страна Анг'),
        ),
        migrations.AlterField(
            model_name='exports',
            name='country_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Страна Узб'),
        ),
        migrations.AlterField(
            model_name='exports',
            name='export_percent_after',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Проценты после'),
        ),
        migrations.AlterField(
            model_name='exports',
            name='export_percent_before',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Проценты до'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='starts',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='good_images',
            name='good_badge',
            field=models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='good_images',
            name='good_img',
            field=models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Загл. Рус'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_tr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Загл. Тур'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_us',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Загл. Анг'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Загл. Узб'),
        ),
        migrations.AlterField(
            model_name='innovations',
            name='innovation_desc_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Тур'),
        ),
        migrations.AlterField(
            model_name='innovations',
            name='innovation_desc_us',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Анг'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='choose_lang',
            field=models.CharField(choices=[('Uzbek', 'O`zbek tili'), ('English', 'English'), ('Russian', 'Русский язык'), ('Turkey', 'Turk dili')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product_bases',
            name='product_bases_desc_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Тур'),
        ),
        migrations.AlterField(
            model_name='product_bases',
            name='product_bases_desc_us',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Анг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Адресса Рус'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None, verbose_name='Адресса Тур'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None, verbose_name='Адресса Анг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_address_list_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Адресса Узб'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_city_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название города Рус'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_city_tr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название города Тур'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_city_us',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название города Анг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_city_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название города Узб'),
        ),
        migrations.CreateModel(
            name='good_section_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_description_uz', models.TextField(null=True, verbose_name='Описание Узб')),
                ('section_description_ru', models.TextField(null=True, verbose_name='Описание Рус')),
                ('section_description_us', models.TextField(blank=True, null=True, verbose_name='Описание Анг')),
                ('section_description_tr', models.TextField(blank=True, null=True, verbose_name='Описание Тур')),
                ('good_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.good_section', verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Описание раздела',
                'verbose_name_plural': '2.4 Продукты -> Раздел -> Описании',
            },
        ),
        migrations.AddField(
            model_name='good_section',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.goods', verbose_name='Название продукта'),
        ),
    ]
