# Generated by Django 3.2.9 on 2021-12-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0002_auto_20211205_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_info',
            new_name='good_info_uz',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='specif',
            new_name='specif_uz',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.AddField(
            model_name='goods',
            name='good_info_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_info_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_info_us',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='specif_ru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='specif_tr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='specif_us',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='goods',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='goods',
            name='title_us',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
