# Generated by Django 3.2.9 on 2021-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0002_exports_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exports',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.AddField(
            model_name='exports',
            name='description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exports',
            name='description_us',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exports',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
    ]
