# Generated by Django 3.2.9 on 2022-01-11 07:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0002_auto_20220108_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': '2 Продукты'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_info',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_short_info',
        ),
        migrations.RemoveField(
            model_name='ecology',
            name='ecology_desc',
        ),
        migrations.RemoveField(
            model_name='exports',
            name='country',
        ),
        migrations.RemoveField(
            model_name='innovations',
            name='innovation_desc',
        ),
        migrations.RemoveField(
            model_name='product_bases',
            name='product_bases_desc',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_address_list',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_city',
        ),
        migrations.AddField(
            model_name='company',
            name='company_info_ru',
            field=models.TextField(null=True, verbose_name='Информация Рус'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_info_tr',
            field=models.TextField(blank=True, verbose_name='Информация Тур'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_info_us',
            field=models.TextField(blank=True, verbose_name='Информация Анг'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_info_uz',
            field=models.TextField(null=True, verbose_name='Информация Узб'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_short_info_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название Рус'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_short_info_tr',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название Тур'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_short_info_us',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название Анг'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_short_info_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название Узб'),
        ),
        migrations.AddField(
            model_name='ecology',
            name='ecology_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание Рус'),
        ),
        migrations.AddField(
            model_name='ecology',
            name='ecology_desc_tr',
            field=models.TextField(blank=True, verbose_name='Описание Тур'),
        ),
        migrations.AddField(
            model_name='ecology',
            name='ecology_desc_us',
            field=models.TextField(blank=True, verbose_name='Описание Анг'),
        ),
        migrations.AddField(
            model_name='ecology',
            name='ecology_desc_uz',
            field=models.TextField(null=True, verbose_name='Описание Узб'),
        ),
        migrations.AddField(
            model_name='exports',
            name='country_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна Рус'),
        ),
        migrations.AddField(
            model_name='exports',
            name='country_tr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Страна Тур'),
        ),
        migrations.AddField(
            model_name='exports',
            name='country_us',
            field=models.CharField(blank=True, max_length=50, verbose_name='Страна Анг'),
        ),
        migrations.AddField(
            model_name='exports',
            name='country_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна Узб'),
        ),
        migrations.AddField(
            model_name='innovations',
            name='innovation_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание Рус'),
        ),
        migrations.AddField(
            model_name='innovations',
            name='innovation_desc_tr',
            field=models.TextField(blank=True, verbose_name='Описание Тур'),
        ),
        migrations.AddField(
            model_name='innovations',
            name='innovation_desc_us',
            field=models.TextField(blank=True, verbose_name='Описание Анг'),
        ),
        migrations.AddField(
            model_name='innovations',
            name='innovation_desc_uz',
            field=models.TextField(null=True, verbose_name='Описание Узб'),
        ),
        migrations.AddField(
            model_name='product_bases',
            name='product_bases_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание Рус'),
        ),
        migrations.AddField(
            model_name='product_bases',
            name='product_bases_desc_tr',
            field=models.TextField(blank=True, verbose_name='Описание Тур'),
        ),
        migrations.AddField(
            model_name='product_bases',
            name='product_bases_desc_us',
            field=models.TextField(blank=True, verbose_name='Описание Анг'),
        ),
        migrations.AddField(
            model_name='product_bases',
            name='product_bases_desc_uz',
            field=models.TextField(null=True, verbose_name='Описание Узб'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_address_list_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), size=None), null=True, size=None, verbose_name='Адресса Рус'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_address_list_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), size=None), blank=True, null=True, size=None, verbose_name='Адресса Тур'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_address_list_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), size=None), blank=True, null=True, size=None, verbose_name='Адресса Анг'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_address_list_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), size=None), null=True, size=None, verbose_name='Адресса Узб'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_city_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название города Рус'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_city_tr',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название города Тур'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_city_us',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название города Анг'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_city_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название города Узб'),
        ),
    ]
