# Generated by Django 3.2.9 on 2021-12-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0003_auto_20211219_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='good_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name_uz', models.CharField(max_length=150)),
                ('section_name_ru', models.CharField(max_length=150)),
                ('section_name_us', models.CharField(blank=True, max_length=150)),
                ('section_name_tr', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Секция Товара',
                'verbose_name_plural': '2.3 Секции Товара',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_ru_list',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_tr_list',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_us_list',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_description_uz_list',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_ru_list',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_tr_list',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_us_list',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='section_name_uz_list',
        ),
        migrations.CreateModel(
            name='good_section_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_description_uz', models.TextField()),
                ('section_description_ru', models.TextField()),
                ('section_description_tr', models.TextField(blank=True)),
                ('section_description_us', models.TextField(blank=True)),
                ('good_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.good_section')),
            ],
            options={
                'verbose_name': 'Описания Секции',
                'verbose_name_plural': '2.4 Описании Секции',
            },
        ),
        migrations.AddField(
            model_name='good_section',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artelApp.goods'),
        ),
    ]
