# Generated by Django 3.2.9 on 2022-01-14 12:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0003_auto_20220113_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='good_section',
            name='section_description_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Описание Рус'),
        ),
        migrations.AddField(
            model_name='good_section',
            name='section_description_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None, verbose_name='Описание Тур'),
        ),
        migrations.AddField(
            model_name='good_section',
            name='section_description_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None, verbose_name='Описание Анг'),
        ),
        migrations.AddField(
            model_name='good_section',
            name='section_description_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Описание Узб'),
        ),
        migrations.AlterField(
            model_name='good_section',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodSection', to='artelApp.goods', verbose_name='Название продукта'),
        ),
        migrations.DeleteModel(
            name='good_section_description',
        ),
    ]
