# Generated by Django 3.2.9 on 2021-12-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0003_auto_20211205_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='about_id',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='about_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='about_id',
        ),
        migrations.DeleteModel(
            name='about',
        ),
        migrations.DeleteModel(
            name='collections',
        ),
    ]
