# Generated by Django 3.2.9 on 2021-12-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0004_auto_20211225_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good_section_description',
            name='section_description_ru',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='good_section_description',
            name='section_description_tr',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='good_section_description',
            name='section_description_us',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='good_section_description',
            name='section_description_uz',
            field=models.CharField(max_length=250),
        ),
    ]
