# Generated by Django 4.0 on 2022-02-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0004_categories_artel_or_texno_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='artel_or_texno_park',
            field=models.CharField(choices=[('artel', 'Artel'), ('texno', 'Texno Park')], default='artel', max_length=20, verbose_name='Artel'),
        ),
    ]
