# Generated by Django 4.0 on 2022-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0004_alter_feedback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
