# Generated by Django 3.2.9 on 2022-01-14 14:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0004_auto_20220114_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good_section',
            name='section_description_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Описание Тур'),
        ),
        migrations.AlterField(
            model_name='good_section',
            name='section_description_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Описание Анг'),
        ),
        migrations.AlterField(
            model_name='good_section',
            name='section_name_tr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Секции Тур'),
        ),
        migrations.AlterField(
            model_name='good_section',
            name='section_name_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None, verbose_name='Секции Анг'),
        ),
    ]
