# Generated by Django 3.2.9 on 2021-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelApp', '0005_auto_20211225_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good_images',
            name='good_badge',
            field=models.ImageField(blank=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='good_images',
            name='good_img',
            field=models.ImageField(blank=True, upload_to='goods/'),
        ),
    ]
