from django.contrib import admin
from .models import *

admin.site.register(languages)
admin.site.register(categories)
admin.site.register(goods)
admin.site.register(good_images)
admin.site.register(good_section)
admin.site.register(good_section_description)
admin.site.register(company)
admin.site.register(info)
admin.site.register(partners)
admin.site.register(exports)
admin.site.register(ecology)
admin.site.register(innovations)
admin.site.register(feedback)
admin.site.register(product_bases)
admin.site.register(services)
admin.site.register(reportsOfLanguage)
admin.site.register(reportsOfCategory)
admin.site.register(reportsOfGood)
admin.site.register(stocks)
